CREATE DATABASE IF NOT EXISTS lab_cars;

USE lab_cars;
DROP TABLE IF EXISTS CARS;

CREATE TABLE CARS (
   car_id bigint not null auto_increment primary key,
   vin	char(25) not null,
   manufacturer VARCHAR(100) NOT NULL,
   model VARCHAR(100) NOT NULL,
   year CHAR(4) NOT NULL,
   color VARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    customer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    address VARCHAR(250) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    zipcode CHAR(10) NOT NULL
);
DROP TABLE IF EXISTS INVOICES;

CREATE TABLE INVOICES(
    invoice_number BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    car_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    salesperson_id BIGINT NOT NULL
);
DROP TABLE IF EXISTS SALESPERSON;

CREATE TABLE SALESPERSON(
    staff_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    store VARCHAR(100) NOT NULL
);
    